GAME_CALC = 'What is the result of the expression?'
GAME_EVEN = 'Answer "yes" if the number is even, otherwise answer "no".'
GAME_GCD = 'Find the greatest common divisor of given numbers.'
GAME_PROGRESSION = 'What number is missing in the progression?'
GAME_PRIME = 'Answer "yes" if given number is prime. Otherwise answer "no".'
